### PR TITLE
P2 Image Recognition MVP

### PR DESCRIPTION
**Pull request by mattdear**
This is the P2 image recognition MVP including a JMS message in/out system with testing. A serialisation and de-serialisation class for JMS message objects with testing. Also, includes currently unused Java ANPR library dependency for number plate recognition.

[JSON Message Serialisation Class](https://github.com/gallenc/solent6Public/blob/p2-imrec/mainProject/parent/commonartifacts/JSONMessage/src/main/java/org/solent/devops/message/jms/JSONMessage.java)

This has been tested in docker and locally on machines before pull request has been created.

### CODE REVIEW

**Comment by mattdear** [comment]
LGTM

**Review by emma12812 — APPROVED** [review]

**Review by KieronGillingham — APPROVED** [review]

**Review by JoshuaAB98 — APPROVED** [review]

**Comment by KieronGillingham** [comment]
I noticed/fixed an problem in `appconfig-service.xml` where a property wasn't set that would've stop the output message being sent when deployed.
Also, the end-to-end testing is not robust and needs reworking.

**Comment by emma12812** [comment]
I have added some Javadoc to the JSONMessage class. This is the first time I have done this so it will need checking over

**Comment by KieronGillingham** [comment]
I've improved the robustness of the end-to-end testing of JMS. This test will still need to be extended once the full functionality of the micro-service is implemented. At the moment the service simply appends the word "processed" to the input it receives and the test confirms that.

**Comment by mattdear** [comment]
> I have added some Javadoc to the JSONMessage class. This is the first time I have done this so it will need checking over

Just to let you know I have checked and the Javadoc is displaying nicely. I have also fixed an error with a merge issue and code is now backup to 100% working.

**Review by Matthewbrook2000 — APPROVED** [review]

**Pull request merged**
